### PR TITLE
update checkSanity function to operate on multi-line strings

### PR DESCRIPTION
**Pull request by rexroof**
this fixes issue #2

### CODE REVIEW

**Comment by jwmach1** [comment]
I merged this in to make it easier for @batmat to pull it into the fork that he has released to https://plugins.jenkins.io/parameterized-scheduler

**Comment by batmat** [comment]
@jwmach1 just noticed this, sorry to have missed the ping. Could you consider marking this repo as deprecated or something? That would be great to clarify for users that https://github.com/jenkinsci/parameterized-scheduler-plugin is supposed to have become the canonical place for Jenkins usage.

Also, obviously, as you're authored that plugin in the first place, I would most welcome you as a maintainer there if you want to. Just tell me so and I'll do that in expedite :-).

Thanks!

**Comment by rexroof** [comment]
@batmat @jwmach1 is there a place in the jenkins plugin page where it indicates the github repo for the plugin in their system?

**Comment by batmat** [comment]
@rexroof GitHub link from the wiki page.

**Pull request merged**
